title: ""
email: ""
description: ""
baseurl: ""
url: "https://glitchy-scratch.github.io"

source: site
markdown: kramdown

plugins:
  - jekyll-autoprefixer
  - jekyll-minifier
  - jekyll-last-modified-at
autoprefixer:
  browsers:
    - ">= 1%"
    - last 1 major version
    - not dead
    - Chrome >= 60
    - Firefox >= 60
    - Edge >= 16
    - iOS >= 10
    - Safari >= 10
    - Android >= 6
    - not Explorer <= 11
  sass:
    sass_dir: assets/css

jekyll-minifier:
  uglifier_args:
    harmony: true
